-- ============================================================================
-- ISO 3166-1 Country List (Official International Standard)
-- Reference: ISO 3166-1 (Alpha-2, Alpha-3, Numeric-3, Country Names)
-- Total Entries: 249 officially assigned country codes
-- Encoding: UTF-8
-- ============================================================================

-- Oracle Database DDL
CREATE TABLE COUNTRY (
  CD_ISO       VARCHAR2(2)  NOT NULL PRIMARY KEY,
  NM_COUNTRY   VARCHAR2(80) NOT NULL,
  NM_PRINTABLE VARCHAR2(80) NOT NULL,
  CD_ISO3      VARCHAR2(3)  NOT NULL,
  CD_COUNTRY   CHAR(3)      NOT NULL
);

-- ANSI SQL / PostgreSQL / MySQL / SQL Server / SQLite DDL
CREATE TABLE IF NOT EXISTS COUNTRY (
  CD_ISO       CHAR(2)      NOT NULL PRIMARY KEY,
  NM_COUNTRY   VARCHAR(80)  NOT NULL,
  NM_PRINTABLE VARCHAR(80)  NOT NULL,
  CD_ISO3      CHAR(3)      NOT NULL,
  CD_COUNTRY   CHAR(3)      NOT NULL
);

-- ============================================================================
-- Data Inserts (249 Countries and Territories)
-- ============================================================================

INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', '004');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AX', 'ÅLAND ISLANDS', 'Åland Islands', 'ALA', '248');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AL', 'ALBANIA', 'Albania', 'ALB', '008');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DZ', 'ALGERIA', 'Algeria', 'DZA', '012');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', '016');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AD', 'ANDORRA', 'Andorra', 'AND', '020');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AO', 'ANGOLA', 'Angola', 'AGO', '024');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AI', 'ANGUILLA', 'Anguilla', 'AIA', '660');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AQ', 'ANTARCTICA', 'Antarctica', 'ATA', '010');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', '028');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AR', 'ARGENTINA', 'Argentina', 'ARG', '032');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AM', 'ARMENIA', 'Armenia', 'ARM', '051');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AW', 'ARUBA', 'Aruba', 'ABW', '533');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AU', 'AUSTRALIA', 'Australia', 'AUS', '036');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AT', 'AUSTRIA', 'Austria', 'AUT', '040');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', '031');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BS', 'BAHAMAS', 'Bahamas', 'BHS', '044');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BH', 'BAHRAIN', 'Bahrain', 'BHR', '048');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BD', 'BANGLADESH', 'Bangladesh', 'BGD', '050');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BB', 'BARBADOS', 'Barbados', 'BRB', '052');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BY', 'BELARUS', 'Belarus', 'BLR', '112');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BE', 'BELGIUM', 'Belgium', 'BEL', '056');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BZ', 'BELIZE', 'Belize', 'BLZ', '084');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BJ', 'BENIN', 'Benin', 'BEN', '204');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BM', 'BERMUDA', 'Bermuda', 'BMU', '060');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BT', 'BHUTAN', 'Bhutan', 'BTN', '064');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BO', 'BOLIVIA, PLURINATIONAL STATE OF', 'Bolivia, Plurinational State of', 'BOL', '068');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', 'Bonaire, Sint Eustatius and Saba', 'BES', '535');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', '070');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BW', 'BOTSWANA', 'Botswana', 'BWA', '072');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BV', 'BOUVET ISLAND', 'Bouvet Island', 'BVT', '074');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BR', 'BRAZIL', 'Brazil', 'BRA', '076');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', 'IOT', '086');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', '096');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BG', 'BULGARIA', 'Bulgaria', 'BGR', '100');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', '854');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BI', 'BURUNDI', 'Burundi', 'BDI', '108');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CV', 'CABO VERDE', 'Cabo Verde', 'CPV', '132');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KH', 'CAMBODIA', 'Cambodia', 'KHM', '116');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CM', 'CAMEROON', 'Cameroon', 'CMR', '120');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CA', 'CANADA', 'Canada', 'CAN', '124');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', '136');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', '140');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TD', 'CHAD', 'Chad', 'TCD', '148');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CL', 'CHILE', 'Chile', 'CHL', '152');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CN', 'CHINA', 'China', 'CHN', '156');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CX', 'CHRISTMAS ISLAND', 'Christmas Island', 'CXR', '162');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', 'CCK', '166');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CO', 'COLOMBIA', 'Colombia', 'COL', '170');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KM', 'COMOROS', 'Comoros', 'COM', '174');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CG', 'CONGO', 'Congo', 'COG', '178');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, The Democratic Republic of the', 'COD', '180');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', '184');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CR', 'COSTA RICA', 'Costa Rica', 'CRI', '188');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CI', 'CÔTE D''IVOIRE', 'Côte d''Ivoire', 'CIV', '384');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HR', 'CROATIA', 'Croatia', 'HRV', '191');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CU', 'CUBA', 'Cuba', 'CUB', '192');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CW', 'CURAÇAO', 'Curaçao', 'CUW', '531');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CY', 'CYPRUS', 'Cyprus', 'CYP', '196');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CZ', 'CZECHIA', 'Czechia', 'CZE', '203');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DK', 'DENMARK', 'Denmark', 'DNK', '208');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', '262');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DM', 'DOMINICA', 'Dominica', 'DMA', '212');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', '214');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EC', 'ECUADOR', 'Ecuador', 'ECU', '218');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EG', 'EGYPT', 'Egypt', 'EGY', '818');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SV', 'EL SALVADOR', 'El Salvador', 'SLV', '222');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', '226');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ER', 'ERITREA', 'Eritrea', 'ERI', '232');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EE', 'ESTONIA', 'Estonia', 'EST', '233');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SZ', 'ESWATINI', 'Eswatini', 'SWZ', '748');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', '231');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', '238');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', '234');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FJ', 'FIJI', 'Fiji', 'FJI', '242');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FI', 'FINLAND', 'Finland', 'FIN', '246');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FR', 'FRANCE', 'France', 'FRA', '250');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', '254');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', '258');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', 'ATF', '260');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GA', 'GABON', 'Gabon', 'GAB', '266');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GM', 'GAMBIA', 'Gambia', 'GMB', '270');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GE', 'GEORGIA', 'Georgia', 'GEO', '268');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DE', 'GERMANY', 'Germany', 'DEU', '276');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GH', 'GHANA', 'Ghana', 'GHA', '288');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', '292');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GR', 'GREECE', 'Greece', 'GRC', '300');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GL', 'GREENLAND', 'Greenland', 'GRL', '304');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GD', 'GRENADA', 'Grenada', 'GRD', '308');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', '312');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GU', 'GUAM', 'Guam', 'GUM', '316');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GT', 'GUATEMALA', 'Guatemala', 'GTM', '320');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GG', 'GUERNSEY', 'Guernsey', 'GGY', '831');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GN', 'GUINEA', 'Guinea', 'GIN', '324');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', '624');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GY', 'GUYANA', 'Guyana', 'GUY', '328');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HT', 'HAITI', 'Haiti', 'HTI', '332');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and McDonald Islands', 'HMD', '334');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', '336');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HN', 'HONDURAS', 'Honduras', 'HND', '340');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HK', 'HONG KONG', 'Hong Kong', 'HKG', '344');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HU', 'HUNGARY', 'Hungary', 'HUN', '348');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IS', 'ICELAND', 'Iceland', 'ISL', '352');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IN', 'INDIA', 'India', 'IND', '356');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ID', 'INDONESIA', 'Indonesia', 'IDN', '360');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', '364');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IQ', 'IRAQ', 'Iraq', 'IRQ', '368');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IE', 'IRELAND', 'Ireland', 'IRL', '372');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IM', 'ISLE OF MAN', 'Isle of Man', 'IMN', '833');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IL', 'ISRAEL', 'Israel', 'ISR', '376');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IT', 'ITALY', 'Italy', 'ITA', '380');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JM', 'JAMAICA', 'Jamaica', 'JAM', '388');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JP', 'JAPAN', 'Japan', 'JPN', '392');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JE', 'JERSEY', 'Jersey', 'JEY', '832');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JO', 'JORDAN', 'Jordan', 'JOR', '400');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', '398');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KE', 'KENYA', 'Kenya', 'KEN', '404');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KI', 'KIRIBATI', 'Kiribati', 'KIR', '296');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'Korea, Democratic People''s Republic of', 'PRK', '408');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', '410');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KW', 'KUWAIT', 'Kuwait', 'KWT', '414');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', '417');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'Lao People''s Democratic Republic', 'LAO', '418');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LV', 'LATVIA', 'Latvia', 'LVA', '428');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LB', 'LEBANON', 'Lebanon', 'LBN', '422');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LS', 'LESOTHO', 'Lesotho', 'LSO', '426');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LR', 'LIBERIA', 'Liberia', 'LBR', '430');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LY', 'LIBYA', 'Libya', 'LBY', '434');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', '438');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LT', 'LITHUANIA', 'Lithuania', 'LTU', '440');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', '442');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MO', 'MACAO', 'Macao', 'MAC', '446');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MG', 'MADAGASCAR', 'Madagascar', 'MDG', '450');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MW', 'MALAWI', 'Malawi', 'MWI', '454');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MY', 'MALAYSIA', 'Malaysia', 'MYS', '458');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MV', 'MALDIVES', 'Maldives', 'MDV', '462');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ML', 'MALI', 'Mali', 'MLI', '466');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MT', 'MALTA', 'Malta', 'MLT', '470');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', '584');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', '474');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MR', 'MAURITANIA', 'Mauritania', 'MRT', '478');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MU', 'MAURITIUS', 'Mauritius', 'MUS', '480');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('YT', 'MAYOTTE', 'Mayotte', 'MYT', '175');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MX', 'MEXICO', 'Mexico', 'MEX', '484');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', '583');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', '498');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MC', 'MONACO', 'Monaco', 'MCO', '492');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MN', 'MONGOLIA', 'Mongolia', 'MNG', '496');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ME', 'MONTENEGRO', 'Montenegro', 'MNE', '499');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MS', 'MONTSERRAT', 'Montserrat', 'MSR', '500');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MA', 'MOROCCO', 'Morocco', 'MAR', '504');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', '508');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MM', 'MYANMAR', 'Myanmar', 'MMR', '104');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NA', 'NAMIBIA', 'Namibia', 'NAM', '516');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NR', 'NAURU', 'Nauru', 'NRU', '520');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NP', 'NEPAL', 'Nepal', 'NPL', '524');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NL', 'NETHERLANDS', 'Netherlands', 'NLD', '528');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', '540');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', '554');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NI', 'NICARAGUA', 'Nicaragua', 'NIC', '558');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NE', 'NIGER', 'Niger', 'NER', '562');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NG', 'NIGERIA', 'Nigeria', 'NGA', '566');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NU', 'NIUE', 'Niue', 'NIU', '570');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', '574');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MK', 'NORTH MACEDONIA', 'North Macedonia', 'MKD', '807');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', '580');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NO', 'NORWAY', 'Norway', 'NOR', '578');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('OM', 'OMAN', 'Oman', 'OMN', '512');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PK', 'PAKISTAN', 'Pakistan', 'PAK', '586');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PW', 'PALAU', 'Palau', 'PLW', '585');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PS', 'PALESTINE, STATE OF', 'Palestine, State of', 'PSE', '275');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PA', 'PANAMA', 'Panama', 'PAN', '591');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', '598');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PY', 'PARAGUAY', 'Paraguay', 'PRY', '600');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PE', 'PERU', 'Peru', 'PER', '604');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PH', 'PHILIPPINES', 'Philippines', 'PHL', '608');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PN', 'PITCAIRN', 'Pitcairn', 'PCN', '612');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PL', 'POLAND', 'Poland', 'POL', '616');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PT', 'PORTUGAL', 'Portugal', 'PRT', '620');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', '630');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('QA', 'QATAR', 'Qatar', 'QAT', '634');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RE', 'RÉUNION', 'Réunion', 'REU', '638');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RO', 'ROMANIA', 'Romania', 'ROU', '642');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', '643');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RW', 'RWANDA', 'Rwanda', 'RWA', '646');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BL', 'SAINT BARTHÉLEMY', 'Saint Barthélemy', 'BLM', '652');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', '654');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', '659');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', '662');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MF', 'SAINT MARTIN (FRENCH PART)', 'Saint Martin (French part)', 'MAF', '663');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', '666');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', '670');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('WS', 'SAMOA', 'Samoa', 'WSM', '882');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SM', 'SAN MARINO', 'San Marino', 'SMR', '674');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', '678');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', '682');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SN', 'SENEGAL', 'Senegal', 'SEN', '686');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RS', 'SERBIA', 'Serbia', 'SRB', '688');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SC', 'SEYCHELLES', 'Seychelles', 'SYC', '690');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', '694');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SG', 'SINGAPORE', 'Singapore', 'SGP', '702');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SX', 'SINT MAARTEN (DUTCH PART)', 'Sint Maarten (Dutch part)', 'SXM', '534');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SK', 'SLOVAKIA', 'Slovakia', 'SVK', '703');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SI', 'SLOVENIA', 'Slovenia', 'SVN', '705');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', '090');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SO', 'SOMALIA', 'Somalia', 'SOM', '706');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', '710');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', 'SGS', '239');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SS', 'SOUTH SUDAN', 'South Sudan', 'SSD', '728');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ES', 'SPAIN', 'Spain', 'ESP', '724');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', '144');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SD', 'SUDAN', 'Sudan', 'SDN', '729');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SR', 'SURINAME', 'Suriname', 'SUR', '740');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', '744');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SE', 'SWEDEN', 'Sweden', 'SWE', '752');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CH', 'SWITZERLAND', 'Switzerland', 'CHE', '756');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', '760');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', '158');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', '762');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', '834');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TH', 'THAILAND', 'Thailand', 'THA', '764');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TL', 'TIMOR-LESTE', 'Timor-Leste', 'TLS', '626');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TG', 'TOGO', 'Togo', 'TGO', '768');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TK', 'TOKELAU', 'Tokelau', 'TKL', '772');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TO', 'TONGA', 'Tonga', 'TON', '776');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', '780');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TN', 'TUNISIA', 'Tunisia', 'TUN', '788');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TR', 'TÜRKIYE', 'Türkiye', 'TUR', '792');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', '795');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', '796');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TV', 'TUVALU', 'Tuvalu', 'TUV', '798');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UG', 'UGANDA', 'Uganda', 'UGA', '800');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UA', 'UKRAINE', 'Ukraine', 'UKR', '804');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', '784');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', '826');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('US', 'UNITED STATES', 'United States', 'USA', '840');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', 'UMI', '581');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UY', 'URUGUAY', 'Uruguay', 'URY', '858');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', '860');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VU', 'VANUATU', 'Vanuatu', 'VUT', '548');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF', 'Venezuela, Bolivarian Republic of', 'VEN', '862');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VN', 'VIET NAM', 'Viet Nam', 'VNM', '704');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', '092');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.S.', 'VIR', '850');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', '876');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', '732');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('YE', 'YEMEN', 'Yemen', 'YEM', '887');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ZM', 'ZAMBIA', 'Zambia', 'ZMB', '894');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', '716');
