-- ============================================================================
-- Lista de Países ISO 3166-1 (Padrão Internacional em Português do Brasil - PT-BR)
-- Referência: ISO 3166-1 (Alpha-2, Alpha-3, Numeric-3, Nomes dos Países)
-- Total de Registros: 249 códigos de países e territórios oficialmente atribuídos
-- Codificação: UTF-8
-- ============================================================================

-- Oracle Database DDL
CREATE TABLE COUNTRY (
  CD_ISO       VARCHAR2(2)  NOT NULL PRIMARY KEY,
  NM_COUNTRY   VARCHAR2(80) NOT NULL,
  NM_PRINTABLE VARCHAR2(80) NOT NULL,
  CD_ISO3      VARCHAR2(3)  NOT NULL,
  CD_COUNTRY   CHAR(3)      NOT NULL
);

-- ANSI SQL / PostgreSQL / MySQL / SQL Server / SQLite DDL
CREATE TABLE IF NOT EXISTS COUNTRY (
  CD_ISO       CHAR(2)      NOT NULL PRIMARY KEY,
  NM_COUNTRY   VARCHAR(80)  NOT NULL,
  NM_PRINTABLE VARCHAR(80)  NOT NULL,
  CD_ISO3      CHAR(3)      NOT NULL,
  CD_COUNTRY   CHAR(3)      NOT NULL
);

-- ============================================================================
-- Carga de Dados (249 Países e Territórios em PT-BR)
-- ============================================================================

INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AF', 'AFEGANISTÃO', 'Afeganistão', 'AFG', '004');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ZA', 'ÁFRICA DO SUL', 'África do Sul', 'ZAF', '710');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AL', 'ALBÂNIA', 'Albânia', 'ALB', '008');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DE', 'ALEMANHA', 'Alemanha', 'DEU', '276');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AD', 'ANDORRA', 'Andorra', 'AND', '020');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AO', 'ANGOLA', 'Angola', 'AGO', '024');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AI', 'ANGUILA', 'Anguila', 'AIA', '660');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AQ', 'ANTÁRTIDA', 'Antártida', 'ATA', '010');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AG', 'ANTÍGUA E BARBUDA', 'Antígua e Barbuda', 'ATG', '028');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SA', 'ARÁBIA SAUDITA', 'Arábia Saudita', 'SAU', '682');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DZ', 'ARGÉLIA', 'Argélia', 'DZA', '012');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AR', 'ARGENTINA', 'Argentina', 'ARG', '032');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AM', 'ARMÊNIA', 'Armênia', 'ARM', '051');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AW', 'ARUBA', 'Aruba', 'ABW', '533');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AU', 'AUSTRÁLIA', 'Austrália', 'AUS', '036');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AT', 'ÁUSTRIA', 'Áustria', 'AUT', '040');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AZ', 'AZERBAIDJÃO', 'Azerbaidjão', 'AZE', '031');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BS', 'BAHAMAS', 'Bahamas', 'BHS', '044');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BD', 'BANGLADESH', 'Bangladesh', 'BGD', '050');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BB', 'BARBADOS', 'Barbados', 'BRB', '052');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BH', 'BAREIN', 'Barein', 'BHR', '048');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BY', 'BELARUS', 'Belarus', 'BLR', '112');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BE', 'BÉLGICA', 'Bélgica', 'BEL', '056');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BZ', 'BELIZE', 'Belize', 'BLZ', '084');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BJ', 'BENIN', 'Benin', 'BEN', '204');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BM', 'BERMUDAS', 'Bermudas', 'BMU', '060');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BO', 'BOLÍVIA, ESTADO PLURINACIONAL DA', 'Bolívia, Estado Plurinacional da', 'BOL', '068');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BQ', 'BONAIRE, SANTO EUSTÁQUIO E SABA', 'Bonaire, Santo Eustáquio e Saba', 'BES', '535');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BA', 'BÓSNIA E HERZEGOVINA', 'Bósnia e Herzegovina', 'BIH', '070');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BW', 'BOTSUANA', 'Botsuana', 'BWA', '072');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BR', 'BRASIL', 'Brasil', 'BRA', '076');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BN', 'BRUNEI', 'Brunei', 'BRN', '096');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BG', 'BULGÁRIA', 'Bulgária', 'BGR', '100');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', '854');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BI', 'BURUNDI', 'Burundi', 'BDI', '108');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BT', 'BUTÃO', 'Butão', 'BTN', '064');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CV', 'CABO VERDE', 'Cabo Verde', 'CPV', '132');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CM', 'CAMARÕES', 'Camarões', 'CMR', '120');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KH', 'CAMBOJA', 'Camboja', 'KHM', '116');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CA', 'CANADÁ', 'Canadá', 'CAN', '124');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('QA', 'CATAR', 'Catar', 'QAT', '634');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KZ', 'CAZAQUISTÃO', 'Cazaquistão', 'KAZ', '398');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TD', 'CHADE', 'Chade', 'TCD', '148');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CL', 'CHILE', 'Chile', 'CHL', '152');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CN', 'CHINA', 'China', 'CHN', '156');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CY', 'CHIPRE', 'Chipre', 'CYP', '196');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SG', 'CINGAPURA', 'Cingapura', 'SGP', '702');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CO', 'COLÔMBIA', 'Colômbia', 'COL', '170');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KM', 'COMORES', 'Comores', 'COM', '174');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CG', 'CONGO', 'Congo', 'COG', '178');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CD', 'CONGO, REPÚBLICA DEMOCRÁTICA DO', 'Congo, República Democrática do', 'COD', '180');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KP', 'COREIA DO NORTE', 'Coreia do Norte', 'PRK', '408');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KR', 'COREIA DO SUL', 'Coreia do Sul', 'KOR', '410');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CI', 'COSTA DO MARFIM', 'Costa do Marfim', 'CIV', '384');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CR', 'COSTA RICA', 'Costa Rica', 'CRI', '188');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HR', 'CROÁCIA', 'Croácia', 'HRV', '191');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CU', 'CUBA', 'Cuba', 'CUB', '192');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CW', 'CURAÇAO', 'Curaçao', 'CUW', '531');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DK', 'DINAMARCA', 'Dinamarca', 'DNK', '208');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DJ', 'DJIBUTI', 'Djibuti', 'DJI', '262');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DM', 'DOMÍNICA', 'Domínica', 'DMA', '212');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EG', 'EGITO', 'Egito', 'EGY', '818');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SV', 'EL SALVADOR', 'El Salvador', 'SLV', '222');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AE', 'EMIRADOS ÁRABES UNIDOS', 'Emirados Árabes Unidos', 'ARE', '784');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EC', 'EQUADOR', 'Equador', 'ECU', '218');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ER', 'ERITREIA', 'Eritreia', 'ERI', '232');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SK', 'ESLOVÁQUIA', 'Eslováquia', 'SVK', '703');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SI', 'ESLOVÊNIA', 'Eslovênia', 'SVN', '705');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ES', 'ESPANHA', 'Espanha', 'ESP', '724');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('US', 'ESTADOS UNIDOS', 'Estados Unidos', 'USA', '840');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EE', 'ESTÔNIA', 'Estônia', 'EST', '233');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SZ', 'ESWATINI', 'Eswatini', 'SWZ', '748');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ET', 'ETIÓPIA', 'Etiópia', 'ETH', '231');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RU', 'FEDERAÇÃO RUSSA', 'Federação Russa', 'RUS', '643');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FJ', 'FIJI', 'Fiji', 'FJI', '242');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PH', 'FILIPINAS', 'Filipinas', 'PHL', '608');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FI', 'FINLÂNDIA', 'Finlândia', 'FIN', '246');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FR', 'FRANÇA', 'França', 'FRA', '250');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GA', 'GABÃO', 'Gabão', 'GAB', '266');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GM', 'GÂMBIA', 'Gâmbia', 'GMB', '270');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GH', 'GANA', 'Gana', 'GHA', '288');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GE', 'GEÓRGIA', 'Geórgia', 'GEO', '268');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GS', 'GEÓRGIA DO SUL E ILHAS SANDWICH DO SUL', 'Geórgia do Sul e Ilhas Sandwich do Sul', 'SGS', '239');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', '292');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GD', 'GRANADA', 'Granada', 'GRD', '308');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GR', 'GRÉCIA', 'Grécia', 'GRC', '300');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GL', 'GROENLÂNDIA', 'Groenlândia', 'GRL', '304');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GP', 'GUADALUPE', 'Guadalupe', 'GLP', '312');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GU', 'GUAM', 'Guam', 'GUM', '316');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GT', 'GUATEMALA', 'Guatemala', 'GTM', '320');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GG', 'GUERNSEY', 'Guernsey', 'GGY', '831');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GY', 'GUIANA', 'Guiana', 'GUY', '328');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GF', 'GUIANA FRANCESA', 'Guiana Francesa', 'GUF', '254');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GN', 'GUINÉ', 'Guiné', 'GIN', '324');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GQ', 'GUINÉ EQUATORIAL', 'Guiné Equatorial', 'GNQ', '226');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GW', 'GUINÉ-BISSAU', 'Guiné-Bissau', 'GNB', '624');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HT', 'HAITI', 'Haiti', 'HTI', '332');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HN', 'HONDURAS', 'Honduras', 'HND', '340');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HK', 'HONG KONG', 'Hong Kong', 'HKG', '344');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HU', 'HUNGRIA', 'Hungria', 'HUN', '348');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('YE', 'IÊMEN', 'Iêmen', 'YEM', '887');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BV', 'ILHA BOUVET', 'Ilha Bouvet', 'BVT', '074');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CX', 'ILHA CHRISTMAS', 'Ilha Christmas', 'CXR', '162');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IM', 'ILHA DE MAN', 'Ilha de Man', 'IMN', '833');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('HM', 'ILHA HEARD E ILHAS MCDONALD', 'Ilha Heard e Ilhas McDonald', 'HMD', '334');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NF', 'ILHA NORFOLK', 'Ilha Norfolk', 'NFK', '574');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AX', 'ILHAS ÅLAND', 'Ilhas Åland', 'ALA', '248');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KY', 'ILHAS CAYMAN', 'Ilhas Cayman', 'CYM', '136');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CC', 'ILHAS COCOS (KEELING)', 'Ilhas Cocos (Keeling)', 'CCK', '166');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CK', 'ILHAS COOK', 'Ilhas Cook', 'COK', '184');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FO', 'ILHAS FAROE', 'Ilhas Faroe', 'FRO', '234');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FK', 'ILHAS MALVINAS', 'Ilhas Malvinas', 'FLK', '238');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MP', 'ILHAS MARIANAS DO NORTE', 'Ilhas Marianas do Norte', 'MNP', '580');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MH', 'ILHAS MARSHALL', 'Ilhas Marshall', 'MHL', '584');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UM', 'ILHAS MENORES DISTANTES DOS ESTADOS UNIDOS', 'Ilhas Menores Distantes dos Estados Unidos', 'UMI', '581');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SB', 'ILHAS SALOMÃO', 'Ilhas Salomão', 'SLB', '090');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TC', 'ILHAS TURKS E CAICOS', 'Ilhas Turks e Caicos', 'TCA', '796');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VG', 'ILHAS VIRGENS BRITÂNICAS', 'Ilhas Virgens Britânicas', 'VGB', '092');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VI', 'ILHAS VIRGENS DOS ESTADOS UNIDOS', 'Ilhas Virgens dos Estados Unidos', 'VIR', '850');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IN', 'ÍNDIA', 'Índia', 'IND', '356');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ID', 'INDONÉSIA', 'Indonésia', 'IDN', '360');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IR', 'IRÃ, REPÚBLICA ISLÂMICA DO', 'Irã, República Islâmica do', 'IRN', '364');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IQ', 'IRAQUE', 'Iraque', 'IRQ', '368');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IE', 'IRLANDA', 'Irlanda', 'IRL', '372');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IS', 'ISLÂNDIA', 'Islândia', 'ISL', '352');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IL', 'ISRAEL', 'Israel', 'ISR', '376');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IT', 'ITÁLIA', 'Itália', 'ITA', '380');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JM', 'JAMAICA', 'Jamaica', 'JAM', '388');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JP', 'JAPÃO', 'Japão', 'JPN', '392');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JE', 'JERSEY', 'Jersey', 'JEY', '832');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('JO', 'JORDÂNIA', 'Jordânia', 'JOR', '400');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KI', 'KIRIBATI', 'Kiribati', 'KIR', '296');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KW', 'KUWAIT', 'Kuwait', 'KWT', '414');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LA', 'LAOS', 'Laos', 'LAO', '418');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LS', 'LESOTO', 'Lesoto', 'LSO', '426');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LV', 'LETÔNIA', 'Letônia', 'LVA', '428');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LB', 'LÍBANO', 'Líbano', 'LBN', '422');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LR', 'LIBÉRIA', 'Libéria', 'LBR', '430');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LY', 'LÍBIA', 'Líbia', 'LBY', '434');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', '438');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LT', 'LITUÂNIA', 'Lituânia', 'LTU', '440');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LU', 'LUXEMBURGO', 'Luxemburgo', 'LUX', '442');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MO', 'MACAU', 'Macau', 'MAC', '446');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MK', 'MACEDÔNIA DO NORTE', 'Macedônia do Norte', 'MKD', '807');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MG', 'MADAGASCAR', 'Madagascar', 'MDG', '450');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('YT', 'MAIOTE', 'Maiote', 'MYT', '175');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MY', 'MALÁSIA', 'Malásia', 'MYS', '458');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MW', 'MALAUI', 'Malaui', 'MWI', '454');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MV', 'MALDIVAS', 'Maldivas', 'MDV', '462');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ML', 'MALI', 'Mali', 'MLI', '466');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MT', 'MALTA', 'Malta', 'MLT', '470');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MA', 'MARROCOS', 'Marrocos', 'MAR', '504');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MQ', 'MARTINICA', 'Martinica', 'MTQ', '474');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MU', 'MAURÍCIO', 'Maurício', 'MUS', '480');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MR', 'MAURITÂNIA', 'Mauritânia', 'MRT', '478');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MX', 'MÉXICO', 'México', 'MEX', '484');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MM', 'MIANMAR', 'Mianmar', 'MMR', '104');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('FM', 'MICRONÉSIA, ESTADOS FEDERADOS DA', 'Micronésia, Estados Federados da', 'FSM', '583');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MZ', 'MOÇAMBIQUE', 'Moçambique', 'MOZ', '508');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MD', 'MOLDÁVIA, REPÚBLICA DA', 'Moldávia, República da', 'MDA', '498');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MC', 'MÔNACO', 'Mônaco', 'MCO', '492');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MN', 'MONGÓLIA', 'Mongólia', 'MNG', '496');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ME', 'MONTENEGRO', 'Montenegro', 'MNE', '499');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MS', 'MONTSERRAT', 'Montserrat', 'MSR', '500');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NA', 'NAMÍBIA', 'Namíbia', 'NAM', '516');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NR', 'NAURU', 'Nauru', 'NRU', '520');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NP', 'NEPAL', 'Nepal', 'NPL', '524');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NI', 'NICARÁGUA', 'Nicarágua', 'NIC', '558');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NE', 'NÍGER', 'Níger', 'NER', '562');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NG', 'NIGÉRIA', 'Nigéria', 'NGA', '566');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NU', 'NIUE', 'Niue', 'NIU', '570');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NO', 'NORUEGA', 'Noruega', 'NOR', '578');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NC', 'NOVA CALEDÔNIA', 'Nova Caledônia', 'NCL', '540');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NZ', 'NOVA ZELÂNDIA', 'Nova Zelândia', 'NZL', '554');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('OM', 'OMÃ', 'Omã', 'OMN', '512');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('NL', 'PAÍSES BAIXOS', 'Países Baixos', 'NLD', '528');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PW', 'PALAU', 'Palau', 'PLW', '585');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PS', 'PALESTINA, ESTADO DA', 'Palestina, Estado da', 'PSE', '275');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PA', 'PANAMÁ', 'Panamá', 'PAN', '591');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PG', 'PAPUA-NOVA GUINÉ', 'Papua-Nova Guiné', 'PNG', '598');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PK', 'PAQUISTÃO', 'Paquistão', 'PAK', '586');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PY', 'PARAGUAI', 'Paraguai', 'PRY', '600');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PE', 'PERU', 'Peru', 'PER', '604');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PN', 'PITCAIRN', 'Pitcairn', 'PCN', '612');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PF', 'POLINÉSIA FRANCESA', 'Polinésia Francesa', 'PYF', '258');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PL', 'POLÔNIA', 'Polônia', 'POL', '616');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PR', 'PORTO RICO', 'Porto Rico', 'PRI', '630');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PT', 'PORTUGAL', 'Portugal', 'PRT', '620');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KE', 'QUÊNIA', 'Quênia', 'KEN', '404');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KG', 'QUIRGUISTÃO', 'Quirguistão', 'KGZ', '417');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('GB', 'REINO UNIDO', 'Reino Unido', 'GBR', '826');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CF', 'REPÚBLICA CENTRO-AFRICANA', 'República Centro-Africana', 'CAF', '140');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('DO', 'REPÚBLICA DOMINICANA', 'República Dominicana', 'DOM', '214');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RE', 'REUNIÃO', 'Reunião', 'REU', '638');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RO', 'ROMÊNIA', 'Romênia', 'ROU', '642');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RW', 'RUANDA', 'Ruanda', 'RWA', '646');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('EH', 'SAARA OCIDENTAL', 'Saara Ocidental', 'ESH', '732');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('WS', 'SAMOA', 'Samoa', 'WSM', '882');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('AS', 'SAMOA AMERICANA', 'Samoa Americana', 'ASM', '016');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SH', 'SANTA HELENA, ASCENSÃO E TRISTÃO DA CUNHA', 'Santa Helena, Ascensão e Tristão da Cunha', 'SHN', '654');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LC', 'SANTA LÚCIA', 'Santa Lúcia', 'LCA', '662');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('BL', 'SÃO BARTOLOMEU', 'São Bartolomeu', 'BLM', '652');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('KN', 'SÃO CRISTÓVÃO E NÉVIS', 'São Cristóvão e Névis', 'KNA', '659');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SM', 'SÃO MARINO', 'São Marino', 'SMR', '674');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('MF', 'SÃO MARTIM (PARTE FRANCESA)', 'São Martim (parte francesa)', 'MAF', '663');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SX', 'SÃO MARTIM (PARTE HOLANDESA)', 'São Martim (parte holandesa)', 'SXM', '534');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('PM', 'SÃO PEDRO E MIQUELON', 'São Pedro e Miquelon', 'SPM', '666');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ST', 'SÃO TOMÉ E PRÍNCIPE', 'São Tomé e Príncipe', 'STP', '678');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VC', 'SÃO VICENTE E GRANADINAS', 'São Vicente e Granadinas', 'VCT', '670');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SN', 'SENEGAL', 'Senegal', 'SEN', '686');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SL', 'SERRA LEOA', 'Serra Leoa', 'SLE', '694');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('RS', 'SÉRVIA', 'Sérvia', 'SRB', '688');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SC', 'SEYCHELLES', 'Seychelles', 'SYC', '690');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SY', 'SÍRIA', 'Síria', 'SYR', '760');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SO', 'SOMÁLIA', 'Somália', 'SOM', '706');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', '144');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SD', 'SUDÃO', 'Sudão', 'SDN', '729');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SS', 'SUDÃO DO SUL', 'Sudão do Sul', 'SSD', '728');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SE', 'SUÉCIA', 'Suécia', 'SWE', '752');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CH', 'SUÍÇA', 'Suíça', 'CHE', '756');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SR', 'SURINAME', 'Suriname', 'SUR', '740');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('SJ', 'SVALBARD E A ILHA DE JAN MAYEN', 'Svalbard e a Ilha de Jan Mayen', 'SJM', '744');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TJ', 'TADJIQUISTÃO', 'Tadjiquistão', 'TJK', '762');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TH', 'TAILÂNDIA', 'Tailândia', 'THA', '764');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TW', 'TAIWAN, PROVÍNCIA DA CHINA', 'Taiwan, Província da China', 'TWN', '158');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TZ', 'TANZÂNIA, REPÚBLICA UNIDA DA', 'Tanzânia, República Unida da', 'TZA', '834');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('CZ', 'TCHÉQUIA', 'Tchéquia', 'CZE', '203');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('IO', 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO', 'Território Britânico do Oceano Índico', 'IOT', '086');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TF', 'TERRITÓRIOS FRANCESES DO SUL', 'Territórios Franceses do Sul', 'ATF', '260');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TL', 'TIMOR-LESTE', 'Timor-Leste', 'TLS', '626');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TG', 'TOGO', 'Togo', 'TGO', '768');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TO', 'TONGA', 'Tonga', 'TON', '776');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TK', 'TOQUELAU', 'Toquelau', 'TKL', '772');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TT', 'TRINIDAD E TOBAGO', 'Trinidad e Tobago', 'TTO', '780');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TN', 'TUNÍSIA', 'Tunísia', 'TUN', '788');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TM', 'TURCOMENISTÃO', 'Turcomenistão', 'TKM', '795');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TR', 'TURQUIA', 'Turquia', 'TUR', '792');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('TV', 'TUVALU', 'Tuvalu', 'TUV', '798');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UA', 'UCRÂNIA', 'Ucrânia', 'UKR', '804');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UG', 'UGANDA', 'Uganda', 'UGA', '800');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UY', 'URUGUAI', 'Uruguai', 'URY', '858');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('UZ', 'UZBEQUISTÃO', 'Uzbequistão', 'UZB', '860');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VU', 'VANUATU', 'Vanuatu', 'VUT', '548');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VA', 'VATICANO', 'Vaticano', 'VAT', '336');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VE', 'VENEZUELA, REPÚBLICA BOLIVARIANA DA', 'Venezuela, República Bolivariana da', 'VEN', '862');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('VN', 'VIETNÃ', 'Vietnã', 'VNM', '704');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('WF', 'WALLIS E FUTUNA', 'Wallis e Futuna', 'WLF', '876');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ZM', 'ZÂMBIA', 'Zâmbia', 'ZMB', '894');
INSERT INTO COUNTRY (CD_ISO, NM_COUNTRY, NM_PRINTABLE, CD_ISO3, CD_COUNTRY) VALUES ('ZW', 'ZIMBÁBUE', 'Zimbábue', 'ZWE', '716');
